/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3135",
        "background": "#f7f9ff",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-variant": "#dfe3e8",
        "primary-fixed-dim": "#93ccff",
        "surface-tint": "#006398",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "outline": "#707881",
        "outline-variant": "#bfc7d2",
        "on-secondary-fixed": "#0b1c30",
        "secondary-container": "#d0e1fb",
        "tertiary": "#894d00",
        "on-surface": "#181c20",
        "inverse-on-surface": "#eef1f7",
        "surface-container-high": "#e5e8ee",
        "tertiary-fixed-dim": "#ffb875",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001d31",
        "on-primary-container": "#fdfcff",
        "on-primary-fixed-variant": "#004b73",
        "on-tertiary-fixed-variant": "#6b3b00",
        "primary-fixed": "#cce5ff",
        "error-container": "#ffdad6",
        "primary": "#006194",
        "surface-bright": "#f7f9ff",
        "on-error": "#ffffff",
        "tertiary-container": "#ac6200",
        "surface-container-highest": "#dfe3e8",
        "surface": "#f7f9ff",
        "on-error-container": "#93000a",
        "secondary": "#505f76",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "surface-dim": "#d7dae0",
        "surface-container-low": "#f1f4fa",
        "on-tertiary-fixed": "#2d1600",
        "inverse-primary": "#93ccff",
        "on-surface-variant": "#3f4850",
        "on-secondary-container": "#54647a",
        "secondary-fixed": "#d3e4fe",
        "primary-container": "#007bb9",
        "tertiary-fixed": "#ffdcc0",
        "on-background": "#181c20",
        "surface-container": "#ebeef4",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "container-max": "1440px",
        "xl": "32px"
      }
    },
  },
  plugins: [],
}
